when i was studyig intermediate i was dreaming to become a software engineer...l
later when i close to engineering course there was no boom for computer science so seniors suggested me to go 
civl or mechanical egineering...so i joined and finished mechanical engg...
after graduation i was dreaming to get techical govt job prepared well was very very close but lost
i feel if i would sit atlease a few more months i must cracked it...
so due to tight situation in house,,,,i joined a mechanical based company..
gained handsome amount and learnt so much knnowledge and gained good name in organizasion..
but some how i felt low myself doing that job since when i compared to my ability and the stage which im in...
and the style of job also not the way which i like...
took very strong and dare step....
left the job and joined the in mithuntechnologies for devops course...
now im in mid of the course ...soon will be written here further updates..

